### ISSUE TITLE
请问可以创建一个armv7的docker镜像吗

### ISSUE THREAD

**Issue by Lynn-Becky** [dextercai/feeyo-adsb-golang#13]

**Comment by dextercai** [comment]
最近三天内处理。

**Comment by Lynn-Becky** [comment]
> 最近三天内处理。

感谢

**Comment by dextercai** [comment]
详见 [v1.5.4](https://github.com/dextercai/feeyo-adsb-golang/releases/tag/v1.5.4)
dockerhub latest已增加armv7镜像
