### ISSUE TITLE
建议增加ADSB解码器

### ISSUE THREAD

**Issue by HLLF-FAN** [dextercai/feeyo-adsb-golang#15]
可融合dump1090或readsb

**Comment by dongqiceo** [comment]
这个可以有，只是打包成一个包，会给使用者带来很多方便，但是希望可以保留目前的打包形式，有时会将解码器跑在异地

**Comment by dextercai** [comment]
从另外两个项目的Licence上来看，我这边MIT的项目直接代码层面融合不太合适。会考虑以Docker的形式，来增加部署的便捷性。

**Comment by HLLF-FAN** [comment]
做成插件的形式也挺好的

**Comment by HLLF-FAN** [comment]
请问解码器多久会推出呢？

**Comment by dextercai** [comment]
建议以官方上传方案为主，第三方在实际使用时不太受飞常准志愿者群体接受。解码器这块目前搁置。

**Comment by sparrowhe** [comment]
> 请问解码器多久会推出呢？

可以自己写个 docker-compose 自己拼一个
