### ISSUE TITLE
关于运行日志的自动清理

### ISSUE THREAD

**Issue by Lynn-Becky** [dextercai/feeyo-adsb-golang#22]
该项目已在开发板运行许久，但由于开发板上的硬盘较小，导致长时间运行后可用储存变小，需要重新部署容器缓解
目前日志大小为2.7g
![image](https://github.com/dextercai/feeyo-adsb-golang/assets/60915579/1357bdec-fc45-45fc-a514-8b412b9eb696)
能否开发自动日志清理，或者借助第三方脚本、平台来实现自动清理脚本，感谢！

**Comment by dextercai** [comment]
本项目正在开发的2.0版本加入了日志轮转机制，可以解决小设备上的日志文件占用问题。

但我从图片猜测你在用docker进行部署，可能与上述该特性无关，图片中的日志应该是docker将stderr/stdout记录下的日志。

可以在docker启动时增加该参数：`--log-opt max-size=10m`，帮助限制日志大小为10m。
docker该特性文档参考可见: https://docs.docker.com/config/containers/logging/local/

如果还有进一步问题，欢迎继续回复。
对2.0版本有功能请求，请在 #21 回复。

**Comment by Lynn-Becky** [comment]
了解，目前已经在启动时添加了该参数，感谢
