### ISSUE TITLE
程序不定时崩溃 Kernel 6.8.8 

### ISSUE THREAD

**Issue by vatprcyq** [dextercai/feeyo-adsb-golang#23]
程序不定时直接退出，回拨消息停在最后一条上传成功
Cron日志显示
runtime: checkdead: find g 1 in status 1
fatal error: checkdead: runnable g
[cron msg(stack).txt](https://github.com/dextercai/feeyo-adsb-golang/files/15187961/cron.msg.stack.txt)

**Comment by dextercai** [comment]
若为自编译，请提供Golang工具链版本。

**Comment by vatprcyq** [comment]
> 若为自编译，请提供Golang工具链版本。

Releases下载的

**Comment by vatprcyq** [comment]
另一份log喵，错误看起来差不多喵
[msg2.txt](https://github.com/dextercai/feeyo-adsb-golang/files/15204355/msg2.txt)

**Comment by dextercai** [comment]
```
Linux LTY-SUSE 6.8.8-1-default #1 SMP PREEMPT_DYNAMIC Mon Apr 29 05:24:46 UTC 2024 (5cd3298) x86_64 x86_64 x86_64 GNU/Linux
```

该Case所使用的Linux内核较新。问题存在于Golang Runtime中，尚不明确。

**Comment by dextercai** [comment]
尝试使用：https://github.com/dextercai/feeyo-adsb-golang/releases/tag/v1.5.5
该版本使用了Go 1.22.3 工具链进行打包编译，可能会缓解问题。

**Comment by vatprcyq** [comment]
已更换1.5.5版本，监控中

**Comment by vatprcyq** [comment]
> 尝试使用：https://github.com/dextercai/feeyo-adsb-golang/releases/tag/v1.5.5 该版本使用了Go 1.22.3 工具链进行打包编译，可能会缓解问题。

换此版本后观察3天暂未发现崩溃。
当前内核版本：
Linux LTY-SUSE 6.9.1-1-default #1 SMP PREEMPT_DYNAMIC Fri May 17 11:59:46 UTC 2024 (0c0b0b5) x86_64 x86_64 x86_64 GNU/Linux

**Comment by dextercai** [comment]
若在未来更新内核版本后，使用1.5.5版本出现类似问题，请打开本issue。
