### ISSUE TITLE
如有任何新特性或需求，欢迎在此提出

### ISSUE THREAD

**Issue by dextercai** [dextercai/feeyo-adsb-golang#4]
如有任何新特性或需求，欢迎在此提出。请勿直接回复本Issue。建议您开设一个新的Issue。

**Comment by psusong** [comment]
你好能直接开发一个docker的版本么？这样群晖就可以用了。

**Comment by dextercai** [comment]
> 你好能直接开发一个docker的版本么？这样群晖就可以用了。

您好，请开一个新的Issues。
