### ISSUE TITLE
能不能开发一个docker的版本？

### ISSUE THREAD

**Issue by psusong** [dextercai/feeyo-adsb-golang#5]
感谢

**Comment by dextercai** [comment]
will support soon. 将于最近完成支持。

**Comment by MrLiu4096** [comment]
我自己搞了一个docker镜像，您可以看看，但是我不知道如何通过设置环境变量来控制conf.ini文件，所以目前还需要手动修改或者编辑好后作为存储卷导入，docker镜像名称：mrgreen1024/feeyo-feed:latest

**Comment by dextercai** [comment]
不建议使用环境变量，conf.ini的设计目标是非容器隔离环境下的运行。建议使用command传参的方式进行运行。

Btw，我目前也正在着手考虑docker镜像的问题。原来计划连dump1090，包括地图那部分都用golang实现一遍的，但因为CGO的一些的问题，还没有想好用怎么样的方案。

不知道你有什么好的建议。

**Comment by Avantyjw** [comment]
> 我自己搞了一个docker镜像，您可以看看，但是我不知道如何通过设置环境变量来控制conf.ini文件，所以目前还需要手动修改或者编辑好后作为存储卷导入，docker镜像名称：mrgreen1024/feeyo-feed:latest

我打算在群晖下部署您的docker文件 想问问我如何映射config的路径？

**Comment by dextercai** [comment]
> > 我自己搞了一个docker镜像，您可以看看，但是我不知道如何通过设置环境变量来控制conf.ini文件，所以目前还需要手动修改或者编辑好后作为存储卷导入，docker镜像名称：mrgreen1024/feeyo-feed:latest
> 
> 我打算在群晖下部署您的docker文件 想问问我如何映射config的路径？

请晚些时候查看本项目，相关的更新将在稍后的PR中合并到主分支。
